package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Adresy generated by hbm2java
 */
public class Adresy  implements java.io.Serializable {


     private Integer idAdresu;
     private String panstwo;
     private String region;
     private String kodPocztowy;
     private String miasto;
     private String ulica;
     private String numerBudynku;
     private String numerLokalu;
     private Set stanies = new HashSet(0);
     private Set uzytkownicies = new HashSet(0);
     private Set magazyns = new HashSet(0);

    public Adresy() {
    }

    public Adresy(String panstwo, String region, String kodPocztowy, String miasto, String ulica, String numerBudynku, String numerLokalu, Set stanies, Set uzytkownicies, Set magazyns) {
       this.panstwo = panstwo;
       this.region = region;
       this.kodPocztowy = kodPocztowy;
       this.miasto = miasto;
       this.ulica = ulica;
       this.numerBudynku = numerBudynku;
       this.numerLokalu = numerLokalu;
       this.stanies = stanies;
       this.uzytkownicies = uzytkownicies;
       this.magazyns = magazyns;
    }
   
    public Integer getIdAdresu() {
        return this.idAdresu;
    }
    
    public void setIdAdresu(Integer idAdresu) {
        this.idAdresu = idAdresu;
    }
    public String getPanstwo() {
        return this.panstwo;
    }
    
    public void setPanstwo(String panstwo) {
        this.panstwo = panstwo;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getKodPocztowy() {
        return this.kodPocztowy;
    }
    
    public void setKodPocztowy(String kodPocztowy) {
        this.kodPocztowy = kodPocztowy;
    }
    public String getMiasto() {
        return this.miasto;
    }
    
    public void setMiasto(String miasto) {
        this.miasto = miasto;
    }
    public String getUlica() {
        return this.ulica;
    }
    
    public void setUlica(String ulica) {
        this.ulica = ulica;
    }
    public String getNumerBudynku() {
        return this.numerBudynku;
    }
    
    public void setNumerBudynku(String numerBudynku) {
        this.numerBudynku = numerBudynku;
    }
    public String getNumerLokalu() {
        return this.numerLokalu;
    }
    
    public void setNumerLokalu(String numerLokalu) {
        this.numerLokalu = numerLokalu;
    }
    public Set getStanies() {
        return this.stanies;
    }
    
    public void setStanies(Set stanies) {
        this.stanies = stanies;
    }
    public Set getUzytkownicies() {
        return this.uzytkownicies;
    }
    
    public void setUzytkownicies(Set uzytkownicies) {
        this.uzytkownicies = uzytkownicies;
    }
    public Set getMagazyns() {
        return this.magazyns;
    }
    
    public void setMagazyns(Set magazyns) {
        this.magazyns = magazyns;
    }




}


