package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Logowania generated by hbm2java
 */
public class Logowania  implements java.io.Serializable {


     private String adresIp;
     private Date ostatnieLogowanie;
     private Integer iloscLogowan;

    public Logowania() {
    }

	
    public Logowania(String adresIp) {
        this.adresIp = adresIp;
    }
    public Logowania(String adresIp, Date ostatnieLogowanie, Integer iloscLogowan) {
       this.adresIp = adresIp;
       this.ostatnieLogowanie = ostatnieLogowanie;
       this.iloscLogowan = iloscLogowan;
    }
   
    public String getAdresIp() {
        return this.adresIp;
    }
    
    public void setAdresIp(String adresIp) {
        this.adresIp = adresIp;
    }
    public Date getOstatnieLogowanie() {
        return this.ostatnieLogowanie;
    }
    
    public void setOstatnieLogowanie(Date ostatnieLogowanie) {
        this.ostatnieLogowanie = ostatnieLogowanie;
    }
    public Integer getIloscLogowan() {
        return this.iloscLogowan;
    }
    
    public void setIloscLogowan(Integer iloscLogowan) {
        this.iloscLogowan = iloscLogowan;
    }




}


