package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1



/**
 * Magazyn generated by hbm2java
 */
public class Magazyn  implements java.io.Serializable {


     private int id;
     private Adresy adresy;
     private String kontaktowyEmail;

    public Magazyn() {
    }

	
    public Magazyn(int id) {
        this.id = id;
    }
    public Magazyn(int id, Adresy adresy, String kontaktowyEmail) {
       this.id = id;
       this.adresy = adresy;
       this.kontaktowyEmail = kontaktowyEmail;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Adresy getAdresy() {
        return this.adresy;
    }
    
    public void setAdresy(Adresy adresy) {
        this.adresy = adresy;
    }
    public String getKontaktowyEmail() {
        return this.kontaktowyEmail;
    }
    
    public void setKontaktowyEmail(String kontaktowyEmail) {
        this.kontaktowyEmail = kontaktowyEmail;
    }




}


