package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Obecnosci generated by hbm2java
 */
public class Obecnosci  implements java.io.Serializable {


     private Integer idObecnosci;
     private Date wejscie;
     private Date wyjscie;

    public Obecnosci() {
    }

    public Obecnosci(Date wejscie, Date wyjscie) {
       this.wejscie = wejscie;
       this.wyjscie = wyjscie;
    }
   
    public Integer getIdObecnosci() {
        return this.idObecnosci;
    }
    
    public void setIdObecnosci(Integer idObecnosci) {
        this.idObecnosci = idObecnosci;
    }
    public Date getWejscie() {
        return this.wejscie;
    }
    
    public void setWejscie(Date wejscie) {
        this.wejscie = wejscie;
    }
    public Date getWyjscie() {
        return this.wyjscie;
    }
    
    public void setWyjscie(Date wyjscie) {
        this.wyjscie = wyjscie;
    }




}


