package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1



/**
 * Obrazyproduktow generated by hbm2java
 */
public class Obrazyproduktow  implements java.io.Serializable {


     private ObrazyproduktowId id;
     private Opisyproduktow opisyproduktow;
     private byte[] obrazek;

    public Obrazyproduktow() {
    }

	
    public Obrazyproduktow(ObrazyproduktowId id, Opisyproduktow opisyproduktow) {
        this.id = id;
        this.opisyproduktow = opisyproduktow;
    }
    public Obrazyproduktow(ObrazyproduktowId id, Opisyproduktow opisyproduktow, byte[] obrazek) {
       this.id = id;
       this.opisyproduktow = opisyproduktow;
       this.obrazek = obrazek;
    }
   
    public ObrazyproduktowId getId() {
        return this.id;
    }
    
    public void setId(ObrazyproduktowId id) {
        this.id = id;
    }
    public Opisyproduktow getOpisyproduktow() {
        return this.opisyproduktow;
    }
    
    public void setOpisyproduktow(Opisyproduktow opisyproduktow) {
        this.opisyproduktow = opisyproduktow;
    }
    public byte[] getObrazek() {
        return this.obrazek;
    }
    
    public void setObrazek(byte[] obrazek) {
        this.obrazek = obrazek;
    }




}


