package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1



/**
 * ObrazyproduktowId generated by hbm2java
 */
public class ObrazyproduktowId  implements java.io.Serializable {


     private int idOpisu;
     private int idObrazka;

    public ObrazyproduktowId() {
    }

    public ObrazyproduktowId(int idOpisu, int idObrazka) {
       this.idOpisu = idOpisu;
       this.idObrazka = idObrazka;
    }
   
    public int getIdOpisu() {
        return this.idOpisu;
    }
    
    public void setIdOpisu(int idOpisu) {
        this.idOpisu = idOpisu;
    }
    public int getIdObrazka() {
        return this.idObrazka;
    }
    
    public void setIdObrazka(int idObrazka) {
        this.idObrazka = idObrazka;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ObrazyproduktowId) ) return false;
		 ObrazyproduktowId castOther = ( ObrazyproduktowId ) other; 
         
		 return (this.getIdOpisu()==castOther.getIdOpisu())
 && (this.getIdObrazka()==castOther.getIdObrazka());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOpisu();
         result = 37 * result + this.getIdObrazka();
         return result;
   }   


}


