package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1



/**
 * OpisyStanyId generated by hbm2java
 */
public class OpisyStanyId  implements java.io.Serializable {


     private int idStanu;
     private int idOpisu;

    public OpisyStanyId() {
    }

    public OpisyStanyId(int idStanu, int idOpisu) {
       this.idStanu = idStanu;
       this.idOpisu = idOpisu;
    }
   
    public int getIdStanu() {
        return this.idStanu;
    }
    
    public void setIdStanu(int idStanu) {
        this.idStanu = idStanu;
    }
    public int getIdOpisu() {
        return this.idOpisu;
    }
    
    public void setIdOpisu(int idOpisu) {
        this.idOpisu = idOpisu;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OpisyStanyId) ) return false;
		 OpisyStanyId castOther = ( OpisyStanyId ) other; 
         
		 return (this.getIdStanu()==castOther.getIdStanu())
 && (this.getIdOpisu()==castOther.getIdOpisu());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdStanu();
         result = 37 * result + this.getIdOpisu();
         return result;
   }   


}


