package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * OpisyStany generated by hbm2java
 */
public class OpisyStany  implements java.io.Serializable {


     private OpisyStanyId id;
     private Opisyproduktow opisyproduktow;
     private Stany stany;
     private BigDecimal ilosc;

    public OpisyStany() {
    }

	
    public OpisyStany(OpisyStanyId id, Opisyproduktow opisyproduktow, Stany stany) {
        this.id = id;
        this.opisyproduktow = opisyproduktow;
        this.stany = stany;
    }
    public OpisyStany(OpisyStanyId id, Opisyproduktow opisyproduktow, Stany stany, BigDecimal ilosc) {
       this.id = id;
       this.opisyproduktow = opisyproduktow;
       this.stany = stany;
       this.ilosc = ilosc;
    }
   
    public OpisyStanyId getId() {
        return this.id;
    }
    
    public void setId(OpisyStanyId id) {
        this.id = id;
    }
    public Opisyproduktow getOpisyproduktow() {
        return this.opisyproduktow;
    }
    
    public void setOpisyproduktow(Opisyproduktow opisyproduktow) {
        this.opisyproduktow = opisyproduktow;
    }
    public Stany getStany() {
        return this.stany;
    }
    
    public void setStany(Stany stany) {
        this.stany = stany;
    }
    public BigDecimal getIlosc() {
        return this.ilosc;
    }
    
    public void setIlosc(BigDecimal ilosc) {
        this.ilosc = ilosc;
    }




}


