package Pojos;

// Generated Jan 1, 2019 10:53:40 PM by Hibernate Tools 4.3.1
import Pojos.Kategorie;
import Pojos.Obrazyproduktow;
import Pojos.OpisyStany;
import Pojos.Uzytkownicy;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Opisyproduktow generated by hbm2java
 */
@Entity
@Table(name = "opisyproduktow",
        catalog = "magazyn_inz"
)
public class Opisyproduktow implements java.io.Serializable {

    private Integer idOpisu;
    private Integer idProduktu;
    private String nazwa;
    private String opis;
    private Integer idWOpakowaniu;
    private Integer opakowaniePo;
    private String kodKreskowy;
    private String rodzajKodu;
    private String producent;
    private String seria;
    private String model;
    private BigDecimal przecena;
    private Integer gwarancja;
    private String rodzajGwarancji;
    private Date terminPrzydatnosci;
    private Date dataProdukcji;
    private BigDecimal cena;
    private BigDecimal ilosc;
    private String rodzajIlosci;
    private String kosztyWysylki;
    private Set<Obrazyproduktow> obrazyproduktows = new HashSet<Obrazyproduktow>(0);
    private Set<Kategorie> kategories = new HashSet<Kategorie>(0);
    private Set<Produkty> produkties = new HashSet<Produkty>(0);
    private Set<Uzytkownicy> uzytkownicies = new HashSet<Uzytkownicy>(0);
    private Set<OpisyStany> opisyStanies = new HashSet<OpisyStany>(0);

    public Opisyproduktow() {
    }

    public Opisyproduktow(String nazwa, String opis, Integer idWOpakowaniu, Integer opakowaniePo, String kodKreskowy, String rodzajKodu, String producent, String seria, String model, BigDecimal przecena, Integer gwarancja, String rodzajGwarancji, Date terminPrzydatnosci, Date dataProdukcji, BigDecimal cena, BigDecimal ilosc, String rodzajIlosci, String kosztyWysylki, Set<Obrazyproduktow> obrazyproduktows, Set<Kategorie> kategories, Set<Produkty> produkties, Set<Uzytkownicy> uzytkownicies, Set<OpisyStany> opisyStanies) {
        this.nazwa = nazwa;
        this.opis = opis;
        this.idWOpakowaniu = idWOpakowaniu;
        this.opakowaniePo = opakowaniePo;
        this.kodKreskowy = kodKreskowy;
        this.rodzajKodu = rodzajKodu;
        this.producent = producent;
        this.seria = seria;
        this.model = model;
        this.przecena = przecena;
        this.gwarancja = gwarancja;
        this.rodzajGwarancji = rodzajGwarancji;
        this.terminPrzydatnosci = terminPrzydatnosci;
        this.dataProdukcji = dataProdukcji;
        this.cena = cena;
        this.ilosc = ilosc;
        this.rodzajIlosci = rodzajIlosci;
        this.kosztyWysylki = kosztyWysylki;
        this.obrazyproduktows = obrazyproduktows;
        this.kategories = kategories;
        this.produkties = produkties;
        this.uzytkownicies = uzytkownicies;
        this.opisyStanies = opisyStanies;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id_opisu", unique = true, nullable = false)
    public Integer getIdOpisu() {
        return this.idOpisu;
    }

    public void setIdOpisu(Integer idOpisu) {
        this.idOpisu = idOpisu;
    }

    @Column(name = "nazwa", length = 45)
    public String getNazwa() {
        return this.nazwa;
    }

    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }

    @Column(name = "opis", length = 45)
    public String getOpis() {
        return this.opis;
    }

    public void setOpis(String opis) {
        this.opis = opis;
    }

    @Column(name = "id_w_opakowaniu")
    public Integer getIdWOpakowaniu() {
        return this.idWOpakowaniu;
    }

    public void setIdWOpakowaniu(Integer idWOpakowaniu) {
        this.idWOpakowaniu = idWOpakowaniu;
    }

    @Column(name = "opakowanie_po")
    public Integer getOpakowaniePo() {
        return this.opakowaniePo;
    }

    public void setOpakowaniePo(Integer opakowaniePo) {
        this.opakowaniePo = opakowaniePo;
    }

    @Column(name = "kod_kreskowy", length = 45)
    public String getKodKreskowy() {
        return this.kodKreskowy;
    }

    public void setKodKreskowy(String kodKreskowy) {
        this.kodKreskowy = kodKreskowy;
    }

    @Column(name = "rodzaj_kodu", length = 45)
    public String getRodzajKodu() {
        return this.rodzajKodu;
    }

    public void setRodzajKodu(String rodzajKodu) {
        this.rodzajKodu = rodzajKodu;
    }

    @Column(name = "producent")
    public String getProducent() {
        return this.producent;
    }

    public void setProducent(String producent) {
        this.producent = producent;
    }

    @Column(name = "seria")
    public String getSeria() {
        return this.seria;
    }

    public void setSeria(String seria) {
        this.seria = seria;
    }

    @Column(name = "model")
    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    @Column(name = "przecena", precision = 5)
    public BigDecimal getPrzecena() {
        return this.przecena;
    }

    public void setPrzecena(BigDecimal przecena) {
        this.przecena = przecena;
    }

    @Column(name = "gwarancja")
    public Integer getGwarancja() {
        return this.gwarancja;
    }

    public void setGwarancja(Integer gwarancja) {
        this.gwarancja = gwarancja;
    }

    @Column(name = "rodzaj_gwarancji", length = 45)
    public String getRodzajGwarancji() {
        return this.rodzajGwarancji;
    }

    public void setRodzajGwarancji(String rodzajGwarancji) {
        this.rodzajGwarancji = rodzajGwarancji;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "termin_przydatnosci", length = 19)
    public Date getTerminPrzydatnosci() {
        return this.terminPrzydatnosci;
    }

    public void setTerminPrzydatnosci(Date terminPrzydatnosci) {
        this.terminPrzydatnosci = terminPrzydatnosci;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "data_produkcji", length = 19)
    public Date getDataProdukcji() {
        return this.dataProdukcji;
    }

    public void setDataProdukcji(Date dataProdukcji) {
        this.dataProdukcji = dataProdukcji;
    }

    @Column(name = "cena", precision = 12, scale = 4)
    public BigDecimal getCena() {
        return this.cena;
    }

    public void setCena(BigDecimal cena) {
        this.cena = cena;
    }

    @Column(name = "ilosc", precision = 10, scale = 4)
    public BigDecimal getIlosc() {
        return this.ilosc;
    }

    public void setIlosc(BigDecimal ilosc) {
        this.ilosc = ilosc;
    }

    @Column(name = "rodzaj_ilosci", length = 45)
    public String getRodzajIlosci() {
        return this.rodzajIlosci;
    }

    public void setRodzajIlosci(String rodzajIlosci) {
        this.rodzajIlosci = rodzajIlosci;
    }

    @Column(name = "koszty_wysylki")
    public String getKosztyWysylki() {
        return this.kosztyWysylki;
    }

    public void setKosztyWysylki(String kosztyWysylki) {
        this.kosztyWysylki = kosztyWysylki;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "opisyproduktow")
    public Set<Obrazyproduktow> getObrazyproduktows() {
        return this.obrazyproduktows;
    }

    public void setObrazyproduktows(Set<Obrazyproduktow> obrazyproduktows) {
        this.obrazyproduktows = obrazyproduktows;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "opisyproduktows")
    public Set<Kategorie> getKategories() {
        return this.kategories;
    }

    public void setKategories(Set<Kategorie> kategories) {
        this.kategories = kategories;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "opisyproduktow")
    public Set<Produkty> getProdukties() {
        return this.produkties;
    }

    public void setProdukties(Set<Produkty> produkties) {
        this.produkties = produkties;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "opisyproduktows")
    public Set<Uzytkownicy> getUzytkownicies() {
        return this.uzytkownicies;
    }

    public void setUzytkownicies(Set<Uzytkownicy> uzytkownicies) {
        this.uzytkownicies = uzytkownicies;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "opisyproduktow")
    public Set<OpisyStany> getOpisyStanies() {
        return this.opisyStanies;
    }

    public void setOpisyStanies(Set<OpisyStany> opisyStanies) {
        this.opisyStanies = opisyStanies;
    }

    public Integer getIdProduktu() {
        return idProduktu;
    }

    public void setIdProduktu(Integer idProduktu) {
        this.idProduktu = idProduktu;
    }

    public static Opisyproduktow mergeWithProdukt(Opisyproduktow op, Produkty p) {
        op.setIdProduktu(p.getIdProduktu());
        if (p.getKodKreskowy() != null && !p.getKodKreskowy().isEmpty()) {
            op.setKodKreskowy(p.getKodKreskowy());
        }
        if (p.getRodzajKodu() != null && !p.getRodzajKodu().isEmpty()) {
            op.setRodzajKodu(p.getRodzajKodu());
        }
        if (p.getIlosc() != null) {
            op.setIlosc(p.getIlosc());
        }
        if (p.getDataProdukcji() != null) {
            op.setDataProdukcji(p.getDataProdukcji());
        }
        if (p.getTerminPrzydatnosci() != null) {
            op.setTerminPrzydatnosci(p.getTerminPrzydatnosci());
        }
        if (p.getGwarancja() != null) {
            op.setGwarancja(p.getGwarancja());
        }
        if (p.getRodzajGwarancji() != null) {
            op.setRodzajGwarancji(p.getRodzajGwarancji());
        }
        if (p.getPrzecena() != null) {
            op.setPrzecena(p.getPrzecena());
        }
        if (p.getCena() != null) {
            op.setCena(p.getCena());
        }
        if (p.getOpis() != null) {
            op.setOpis(p.getOpis());
        }
        
        return op;
    }

    public Opisyproduktow copy() {
        Opisyproduktow copied = new Opisyproduktow();
        copied.cena = this.cena;
        copied.dataProdukcji = this.dataProdukcji;
        copied.gwarancja = this.gwarancja;
        copied.idOpisu = this.idOpisu;
        copied.idProduktu = this.idProduktu;
        copied.idWOpakowaniu = this.idWOpakowaniu;
        copied.ilosc = this.ilosc;
        if (this.kategories != null) {
            copied.kategories = new HashSet();
            for (Kategorie kFrom : this.kategories) {
                copied.kategories.add(kFrom);
            }
        }
        copied.kodKreskowy = this.kodKreskowy;
        copied.kosztyWysylki = this.kosztyWysylki;
        copied.model = this.model;
        copied.nazwa = this.nazwa;
        if (this.obrazyproduktows != null) {
            copied.obrazyproduktows = new HashSet();
            for (Obrazyproduktow opFrom : this.obrazyproduktows) {
                copied.obrazyproduktows.add(opFrom);
            }
        }
        copied.opakowaniePo = this.opakowaniePo;
        copied.opis = this.opis;
        if (this.opisyStanies != null) {
            copied.opisyStanies = new HashSet();
            for (OpisyStany osFrom : this.opisyStanies) {
                copied.opisyStanies.add(osFrom);
            }
        }
        copied.producent = this.producent;
        if (this.produkties != null) {
            copied.produkties = new HashSet();
            for (Produkty p : this.produkties) {
                copied.produkties.add(p);
            }
        }
        copied.przecena = this.przecena;
        copied.rodzajGwarancji = this.rodzajGwarancji;
        copied.rodzajIlosci = this.rodzajIlosci;
        copied.rodzajKodu = this.rodzajKodu;
        copied.seria = this.seria;
        copied.terminPrzydatnosci = this.terminPrzydatnosci;
        if (this.uzytkownicies != null) {
            copied.uzytkownicies = new HashSet();
            for (Uzytkownicy u : this.uzytkownicies) {
                copied.uzytkownicies.add(u);
            }
        }

        return copied;
    }

}
