package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pracownicy generated by hbm2java
 */
public class Pracownicy  implements java.io.Serializable {


     private Integer idPracownika;
     private Stanowiska stanowiska;
     private Date stanowiskoOd;
     private BigDecimal premiaStala;
     private BigDecimal premiaJednorazowa;
     private Integer idUzytkownika;
     private String nrKonta;
     private Date zaplaconeDo;
     private Integer WTrakciePlatnosci;
     private Set urlopyzwolnienias = new HashSet(0);
     private Set zmianies = new HashSet(0);
     private Set stanies = new HashSet(0);

    public Pracownicy() {
    }

    public Pracownicy(Stanowiska stanowiska, Date stanowiskoOd, BigDecimal premiaStala, BigDecimal premiaJednorazowa, Integer idUzytkownika, String nrKonta, Date zaplaconeDo, Integer WTrakciePlatnosci, Set urlopyzwolnienias, Set zmianies, Set stanies) {
       this.stanowiska = stanowiska;
       this.stanowiskoOd = stanowiskoOd;
       this.premiaStala = premiaStala;
       this.premiaJednorazowa = premiaJednorazowa;
       this.idUzytkownika = idUzytkownika;
       this.nrKonta = nrKonta;
       this.zaplaconeDo = zaplaconeDo;
       this.WTrakciePlatnosci = WTrakciePlatnosci;
       this.urlopyzwolnienias = urlopyzwolnienias;
       this.zmianies = zmianies;
       this.stanies = stanies;
    }
   
    public Integer getIdPracownika() {
        return this.idPracownika;
    }
    
    public void setIdPracownika(Integer idPracownika) {
        this.idPracownika = idPracownika;
    }
    public Stanowiska getStanowiska() {
        return this.stanowiska;
    }
    
    public void setStanowiska(Stanowiska stanowiska) {
        this.stanowiska = stanowiska;
    }
    public Date getStanowiskoOd() {
        return this.stanowiskoOd;
    }
    
    public void setStanowiskoOd(Date stanowiskoOd) {
        this.stanowiskoOd = stanowiskoOd;
    }
    public BigDecimal getPremiaStala() {
        return this.premiaStala;
    }
    
    public void setPremiaStala(BigDecimal premiaStala) {
        this.premiaStala = premiaStala;
    }
    public BigDecimal getPremiaJednorazowa() {
        return this.premiaJednorazowa;
    }
    
    public void setPremiaJednorazowa(BigDecimal premiaJednorazowa) {
        this.premiaJednorazowa = premiaJednorazowa;
    }
    public Integer getIdUzytkownika() {
        return this.idUzytkownika;
    }
    
    public void setIdUzytkownika(Integer idUzytkownika) {
        this.idUzytkownika = idUzytkownika;
    }
    public String getNrKonta() {
        return this.nrKonta;
    }
    
    public void setNrKonta(String nrKonta) {
        this.nrKonta = nrKonta;
    }
    public Date getZaplaconeDo() {
        return this.zaplaconeDo;
    }
    
    public void setZaplaconeDo(Date zaplaconeDo) {
        this.zaplaconeDo = zaplaconeDo;
    }
    public Integer getWTrakciePlatnosci() {
        return this.WTrakciePlatnosci;
    }
    
    public void setWTrakciePlatnosci(Integer WTrakciePlatnosci) {
        this.WTrakciePlatnosci = WTrakciePlatnosci;
    }
    public Set getUrlopyzwolnienias() {
        return this.urlopyzwolnienias;
    }
    
    public void setUrlopyzwolnienias(Set urlopyzwolnienias) {
        this.urlopyzwolnienias = urlopyzwolnienias;
    }
    public Set getZmianies() {
        return this.zmianies;
    }
    
    public void setZmianies(Set zmianies) {
        this.zmianies = zmianies;
    }
    public Set getStanies() {
        return this.stanies;
    }
    
    public void setStanies(Set stanies) {
        this.stanies = stanies;
    }




}


