package Pojos;






// Generated Jan 1, 2019 10:53:40 PM by Hibernate Tools 4.3.1


import Pojos.ProduktySegmenty;
import Pojos.ProduktyStany;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Produkty generated by hbm2java
 */
@Entity
@Table(name="produkty"
    ,catalog="magazyn_inz"
)
public class Produkty  implements java.io.Serializable {


     private Integer idProduktu;
     private Opisyproduktow opisyproduktow;
     private String kodKreskowy;
     private String rodzajKodu;
     private BigDecimal ilosc;
     private Date dataProdukcji;
     private Date terminPrzydatnosci;
     private Integer gwarancja;
     private String rodzajGwarancji;
     private BigDecimal przecena;
     private BigDecimal cena;
     private String opis;
     private Set<ProduktyStany> produktyStanies = new HashSet<ProduktyStany>(0);
     private Set<ProduktySegmenty> produktySegmenties = new HashSet<ProduktySegmenty>(0);

    public Produkty() {
    }

    public Produkty(Opisyproduktow opisyproduktow, String kodKreskowy, String rodzajKodu, BigDecimal ilosc, Date dataProdukcji, Date terminPrzydatnosci, Integer gwarancja, String rodzajGwarancji, BigDecimal przecena, BigDecimal cena, String opis, Set<ProduktyStany> produktyStanies, Set<ProduktySegmenty> produktySegmenties) {
       this.opisyproduktow = opisyproduktow;
       this.kodKreskowy = kodKreskowy;
       this.rodzajKodu = rodzajKodu;
       this.ilosc = ilosc;
       this.dataProdukcji = dataProdukcji;
       this.terminPrzydatnosci = terminPrzydatnosci;
       this.gwarancja = gwarancja;
       this.rodzajGwarancji = rodzajGwarancji;
       this.przecena = przecena;
       this.cena = cena;
       this.opis = opis;
       this.produktyStanies = produktyStanies;
       this.produktySegmenties = produktySegmenties;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_produktu", unique=true, nullable=false)
    public Integer getIdProduktu() {
        return this.idProduktu;
    }
    
    public void setIdProduktu(Integer idProduktu) {
        this.idProduktu = idProduktu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_opisu")
    public Opisyproduktow getOpisyproduktow() {
        return this.opisyproduktow;
    }
    
    public void setOpisyproduktow(Opisyproduktow opisyproduktow) {
        this.opisyproduktow = opisyproduktow;
    }

    
    @Column(name="kod_kreskowy", length=45)
    public String getKodKreskowy() {
        return this.kodKreskowy;
    }
    
    public void setKodKreskowy(String kodKreskowy) {
        this.kodKreskowy = kodKreskowy;
    }

    
    @Column(name="rodzaj_kodu", length=45)
    public String getRodzajKodu() {
        return this.rodzajKodu;
    }
    
    public void setRodzajKodu(String rodzajKodu) {
        this.rodzajKodu = rodzajKodu;
    }

    
    @Column(name="ilosc", precision=10, scale=4)
    public BigDecimal getIlosc() {
        return this.ilosc;
    }
    
    public void setIlosc(BigDecimal ilosc) {
        this.ilosc = ilosc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_produkcji", length=10)
    public Date getDataProdukcji() {
        return this.dataProdukcji;
    }
    
    public void setDataProdukcji(Date dataProdukcji) {
        this.dataProdukcji = dataProdukcji;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="termin_przydatnosci", length=19)
    public Date getTerminPrzydatnosci() {
        return this.terminPrzydatnosci;
    }
    
    public void setTerminPrzydatnosci(Date terminPrzydatnosci) {
        this.terminPrzydatnosci = terminPrzydatnosci;
    }

    
    @Column(name="gwarancja")
    public Integer getGwarancja() {
        return this.gwarancja;
    }
    
    public void setGwarancja(Integer gwarancja) {
        this.gwarancja = gwarancja;
    }

    
    @Column(name="rodzaj_gwarancji", length=45)
    public String getRodzajGwarancji() {
        return this.rodzajGwarancji;
    }
    
    public void setRodzajGwarancji(String rodzajGwarancji) {
        this.rodzajGwarancji = rodzajGwarancji;
    }

    
    @Column(name="przecena", precision=5)
    public BigDecimal getPrzecena() {
        return this.przecena;
    }
    
    public void setPrzecena(BigDecimal przecena) {
        this.przecena = przecena;
    }

    
    @Column(name="cena", precision=12, scale=4)
    public BigDecimal getCena() {
        return this.cena;
    }
    
    public void setCena(BigDecimal cena) {
        this.cena = cena;
    }

    
    @Column(name="opis")
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produkty")
    public Set<ProduktyStany> getProduktyStanies() {
        return this.produktyStanies;
    }
    
    public void setProduktyStanies(Set<ProduktyStany> produktyStanies) {
        this.produktyStanies = produktyStanies;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="produkty")
    public Set<ProduktySegmenty> getProduktySegmenties() {
        return this.produktySegmenties;
    }
    
    public void setProduktySegmenties(Set<ProduktySegmenty> produktySegmenties) {
        this.produktySegmenties = produktySegmenties;
    }

public Produkty extractProduktFromOpis(Produkty p, Opisyproduktow op){
        //this.idOpisu = op.getIdOpisu();
        p.kodKreskowy = op.getKodKreskowy();
        p.rodzajKodu = op.getRodzajKodu();
        p.ilosc = op.getIlosc();
        p.dataProdukcji = op.getDataProdukcji();
        p.terminPrzydatnosci = op.getTerminPrzydatnosci();
        p.gwarancja = op.getGwarancja();
        p.rodzajGwarancji = op.getRodzajGwarancji();
        p.przecena = op.getPrzecena();
        p.cena = op.getCena();
        p.opis = op.getOpis();
        p.setOpisyproduktow(op);
        return p;
    }
    
    public Produkty copy(){
        Produkty p = new Produkty();
        p.idProduktu = this.idProduktu;
        p.opisyproduktow = this.opisyproduktow;
        p.kodKreskowy = this.kodKreskowy;
        p.rodzajKodu = this.rodzajKodu;
        p.ilosc = this.ilosc;
        p.dataProdukcji = this.dataProdukcji;
        p.terminPrzydatnosci = this.terminPrzydatnosci;
        p.gwarancja = this.gwarancja;
        p.rodzajGwarancji = this.rodzajGwarancji;
        p.przecena = this.przecena;
        p.cena = this.cena;
        p.opis = this.opis;
        /*if (this.produktyStanies != null) {
            p.produktyStanies = new HashSet();
            for (ProduktyStany psFrom : this.produktyStanies) {
                p.produktyStanies.add(psFrom);
            }
        }*/
        /*if (this.produktySegmenties != null) {
            p.produktySegmenties = new HashSet();
            for (ProduktySegmenty psFrom : this.produktySegmenties) {
                p.produktySegmenties.add(psFrom);
            }
        }
        */
        return p;
    }
}


