package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ProduktyStany generated by hbm2java
 */
public class ProduktyStany  implements java.io.Serializable {


     private ProduktyStanyId id;
     private Produkty produkty;
     private Stany stany;
     private BigDecimal ilosc;

    public ProduktyStany() {
    }

	
    public ProduktyStany(ProduktyStanyId id, Produkty produkty, Stany stany) {
        this.id = id;
        this.produkty = produkty;
        this.stany = stany;
    }
    public ProduktyStany(ProduktyStanyId id, Produkty produkty, Stany stany, BigDecimal ilosc) {
       this.id = id;
       this.produkty = produkty;
       this.stany = stany;
       this.ilosc = ilosc;
    }
   
    public ProduktyStanyId getId() {
        return this.id;
    }
    
    public void setId(ProduktyStanyId id) {
        this.id = id;
    }
    public Produkty getProdukty() {
        return this.produkty;
    }
    
    public void setProdukty(Produkty produkty) {
        this.produkty = produkty;
    }
    public Stany getStany() {
        return this.stany;
    }
    
    public void setStany(Stany stany) {
        this.stany = stany;
    }
    public BigDecimal getIlosc() {
        return this.ilosc;
    }
    
    public void setIlosc(BigDecimal ilosc) {
        this.ilosc = ilosc;
    }




}


