package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1



/**
 * ProduktyStanyId generated by hbm2java
 */
public class ProduktyStanyId  implements java.io.Serializable {


     private int idProduktu;
     private int idStanu;

    public ProduktyStanyId() {
    }

    public ProduktyStanyId(int idProduktu, int idStanu) {
       this.idProduktu = idProduktu;
       this.idStanu = idStanu;
    }
   
    public int getIdProduktu() {
        return this.idProduktu;
    }
    
    public void setIdProduktu(int idProduktu) {
        this.idProduktu = idProduktu;
    }
    public int getIdStanu() {
        return this.idStanu;
    }
    
    public void setIdStanu(int idStanu) {
        this.idStanu = idStanu;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProduktyStanyId) ) return false;
		 ProduktyStanyId castOther = ( ProduktyStanyId ) other; 
         
		 return (this.getIdProduktu()==castOther.getIdProduktu())
 && (this.getIdStanu()==castOther.getIdStanu());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProduktu();
         result = 37 * result + this.getIdStanu();
         return result;
   }   


}


