package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1



/**
 * ProduktySegmenty generated by hbm2java
 */
public class ProduktySegmenty  implements java.io.Serializable {


     private ProduktySegmentyId id;
     private Produkty produkty;

    public ProduktySegmenty() {
    }

    public ProduktySegmenty(ProduktySegmentyId id, Produkty produkty) {
       this.id = id;
       this.produkty = produkty;
    }
   
    public ProduktySegmentyId getId() {
        return this.id;
    }
    
    public void setId(ProduktySegmentyId id) {
        this.id = id;
    }
    public Produkty getProdukty() {
        return this.produkty;
    }
    
    public void setProdukty(Produkty produkty) {
        this.produkty = produkty;
    }




}


