package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Stanowiska generated by hbm2java
 */
public class Stanowiska  implements java.io.Serializable {


     private Integer idStanowiska;
     private String nazwa;
     private String opis;
     private BigDecimal stawka;
     private BigDecimal premiaStala;
     private BigDecimal premiaJednorazowa;
     private Set pracownicies = new HashSet(0);

    public Stanowiska() {
    }

    public Stanowiska(String nazwa, String opis, BigDecimal stawka, BigDecimal premiaStala, BigDecimal premiaJednorazowa, Set pracownicies) {
       this.nazwa = nazwa;
       this.opis = opis;
       this.stawka = stawka;
       this.premiaStala = premiaStala;
       this.premiaJednorazowa = premiaJednorazowa;
       this.pracownicies = pracownicies;
    }
   
    public Integer getIdStanowiska() {
        return this.idStanowiska;
    }
    
    public void setIdStanowiska(Integer idStanowiska) {
        this.idStanowiska = idStanowiska;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public BigDecimal getStawka() {
        return this.stawka;
    }
    
    public void setStawka(BigDecimal stawka) {
        this.stawka = stawka;
    }
    public BigDecimal getPremiaStala() {
        return this.premiaStala;
    }
    
    public void setPremiaStala(BigDecimal premiaStala) {
        this.premiaStala = premiaStala;
    }
    public BigDecimal getPremiaJednorazowa() {
        return this.premiaJednorazowa;
    }
    
    public void setPremiaJednorazowa(BigDecimal premiaJednorazowa) {
        this.premiaJednorazowa = premiaJednorazowa;
    }
    public Set getPracownicies() {
        return this.pracownicies;
    }
    
    public void setPracownicies(Set pracownicies) {
        this.pracownicies = pracownicies;
    }




}


