package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Stany generated by hbm2java
 */
public class Stany  implements java.io.Serializable {


     private Integer idStanu;
     private Adresy adresy;
     private Pracownicy pracownicy;
     private Stany stany;
     private Uzytkownicy uzytkownicy;
     private String nazwaStanu;
     private Date dataRozpoczecia;
     private Date dataZakonczenia;
     private String dodatkoweInformacje;
     private Date koniecGwarancji;
     private Date poczatekNaprawy;
     private Date koniecNaprawy;
     private Set urzadzenias = new HashSet(0);
     private Set produktyStanies = new HashSet(0);
     private Set stanies = new HashSet(0);
     private Set dostawies = new HashSet(0);
     private Set opisyStanies = new HashSet(0);

    public Stany() {
    }

    public Stany(Adresy adresy, Pracownicy pracownicy, Stany stany, Uzytkownicy uzytkownicy, String nazwaStanu, Date dataRozpoczecia, Date dataZakonczenia, String dodatkoweInformacje, Date koniecGwarancji, Date poczatekNaprawy, Date koniecNaprawy, Set urzadzenias, Set produktyStanies, Set stanies, Set dostawies, Set opisyStanies) {
       this.adresy = adresy;
       this.pracownicy = pracownicy;
       this.stany = stany;
       this.uzytkownicy = uzytkownicy;
       this.nazwaStanu = nazwaStanu;
       this.dataRozpoczecia = dataRozpoczecia;
       this.dataZakonczenia = dataZakonczenia;
       this.dodatkoweInformacje = dodatkoweInformacje;
       this.koniecGwarancji = koniecGwarancji;
       this.poczatekNaprawy = poczatekNaprawy;
       this.koniecNaprawy = koniecNaprawy;
       this.urzadzenias = urzadzenias;
       this.produktyStanies = produktyStanies;
       this.stanies = stanies;
       this.dostawies = dostawies;
       this.opisyStanies = opisyStanies;
    }
   
    public Integer getIdStanu() {
        return this.idStanu;
    }
    
    public void setIdStanu(Integer idStanu) {
        this.idStanu = idStanu;
    }
    public Adresy getAdresy() {
        return this.adresy;
    }
    
    public void setAdresy(Adresy adresy) {
        this.adresy = adresy;
    }
    public Pracownicy getPracownicy() {
        return this.pracownicy;
    }
    
    public void setPracownicy(Pracownicy pracownicy) {
        this.pracownicy = pracownicy;
    }
    public Stany getStany() {
        return this.stany;
    }
    
    public void setStany(Stany stany) {
        this.stany = stany;
    }
    public Uzytkownicy getUzytkownicy() {
        return this.uzytkownicy;
    }
    
    public void setUzytkownicy(Uzytkownicy uzytkownicy) {
        this.uzytkownicy = uzytkownicy;
    }
    public String getNazwaStanu() {
        return this.nazwaStanu;
    }
    
    public void setNazwaStanu(String nazwaStanu) {
        this.nazwaStanu = nazwaStanu;
    }
    public Date getDataRozpoczecia() {
        return this.dataRozpoczecia;
    }
    
    public void setDataRozpoczecia(Date dataRozpoczecia) {
        this.dataRozpoczecia = dataRozpoczecia;
    }
    public Date getDataZakonczenia() {
        return this.dataZakonczenia;
    }
    
    public void setDataZakonczenia(Date dataZakonczenia) {
        this.dataZakonczenia = dataZakonczenia;
    }
    public String getDodatkoweInformacje() {
        return this.dodatkoweInformacje;
    }
    
    public void setDodatkoweInformacje(String dodatkoweInformacje) {
        this.dodatkoweInformacje = dodatkoweInformacje;
    }
    public Date getKoniecGwarancji() {
        return this.koniecGwarancji;
    }
    
    public void setKoniecGwarancji(Date koniecGwarancji) {
        this.koniecGwarancji = koniecGwarancji;
    }
    public Date getPoczatekNaprawy() {
        return this.poczatekNaprawy;
    }
    
    public void setPoczatekNaprawy(Date poczatekNaprawy) {
        this.poczatekNaprawy = poczatekNaprawy;
    }
    public Date getKoniecNaprawy() {
        return this.koniecNaprawy;
    }
    
    public void setKoniecNaprawy(Date koniecNaprawy) {
        this.koniecNaprawy = koniecNaprawy;
    }
    public Set getUrzadzenias() {
        return this.urzadzenias;
    }
    
    public void setUrzadzenias(Set urzadzenias) {
        this.urzadzenias = urzadzenias;
    }
    public Set getProduktyStanies() {
        return this.produktyStanies;
    }
    
    public void setProduktyStanies(Set produktyStanies) {
        this.produktyStanies = produktyStanies;
    }
    public Set getStanies() {
        return this.stanies;
    }
    
    public void setStanies(Set stanies) {
        this.stanies = stanies;
    }
    public Set getDostawies() {
        return this.dostawies;
    }
    
    public void setDostawies(Set dostawies) {
        this.dostawies = dostawies;
    }
    public Set getOpisyStanies() {
        return this.opisyStanies;
    }
    
    public void setOpisyStanies(Set opisyStanies) {
        this.opisyStanies = opisyStanies;
    }




}


