package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Urzadzenia generated by hbm2java
 */
public class Urzadzenia  implements java.io.Serializable {


     private Integer idUrzadzenia;
     private String nazwa;
     private Date ostatniSerwis;
     private Set stanies = new HashSet(0);

    public Urzadzenia() {
    }

    public Urzadzenia(String nazwa, Date ostatniSerwis, Set stanies) {
       this.nazwa = nazwa;
       this.ostatniSerwis = ostatniSerwis;
       this.stanies = stanies;
    }
   
    public Integer getIdUrzadzenia() {
        return this.idUrzadzenia;
    }
    
    public void setIdUrzadzenia(Integer idUrzadzenia) {
        this.idUrzadzenia = idUrzadzenia;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public Date getOstatniSerwis() {
        return this.ostatniSerwis;
    }
    
    public void setOstatniSerwis(Date ostatniSerwis) {
        this.ostatniSerwis = ostatniSerwis;
    }
    public Set getStanies() {
        return this.stanies;
    }
    
    public void setStanies(Set stanies) {
        this.stanies = stanies;
    }




}


