package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Uzytkownicy generated by hbm2java
 */
public class Uzytkownicy  implements java.io.Serializable {


     private Integer idUzytkownika;
     private String login;
     private String haslo;
     private String imie;
     private String nazwisko;
     private String email;
     private String rodzajUzytkownika;
     private Set stanies = new HashSet(0);
     private Set adresies = new HashSet(0);
     private Set opisyproduktows = new HashSet(0);

    public Uzytkownicy() {
    }

    public Uzytkownicy(String login, String haslo, String imie, String nazwisko, String email, String rodzajUzytkownika, Set stanies, Set adresies, Set opisyproduktows) {
       this.login = login;
       this.haslo = haslo;
       this.imie = imie;
       this.nazwisko = nazwisko;
       this.email = email;
       this.rodzajUzytkownika = rodzajUzytkownika;
       this.stanies = stanies;
       this.adresies = adresies;
       this.opisyproduktows = opisyproduktows;
    }
   
    public Integer getIdUzytkownika() {
        return this.idUzytkownika;
    }
    
    public void setIdUzytkownika(Integer idUzytkownika) {
        this.idUzytkownika = idUzytkownika;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getHaslo() {
        return this.haslo;
    }
    
    public void setHaslo(String haslo) {
        this.haslo = haslo;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getRodzajUzytkownika() {
        return this.rodzajUzytkownika;
    }
    
    public void setRodzajUzytkownika(String rodzajUzytkownika) {
        this.rodzajUzytkownika = rodzajUzytkownika;
    }
    public Set getStanies() {
        return this.stanies;
    }
    
    public void setStanies(Set stanies) {
        this.stanies = stanies;
    }
    public Set getAdresies() {
        return this.adresies;
    }
    
    public void setAdresies(Set adresies) {
        this.adresies = adresies;
    }
    public Set getOpisyproduktows() {
        return this.opisyproduktows;
    }
    
    public void setOpisyproduktows(Set opisyproduktows) {
        this.opisyproduktows = opisyproduktows;
    }




}


