package Pojos;






// Generated Jan 11, 2019 3:58:09 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Zmiany generated by hbm2java
 */
public class Zmiany  implements java.io.Serializable {


     private Integer idZmiany;
     private Date rozpoczecie;
     private Date zakonczenie;
     private Set pracownicies = new HashSet(0);

    public Zmiany() {
    }

    public Zmiany(Date rozpoczecie, Date zakonczenie, Set pracownicies) {
       this.rozpoczecie = rozpoczecie;
       this.zakonczenie = zakonczenie;
       this.pracownicies = pracownicies;
    }
   
    public Integer getIdZmiany() {
        return this.idZmiany;
    }
    
    public void setIdZmiany(Integer idZmiany) {
        this.idZmiany = idZmiany;
    }
    public Date getRozpoczecie() {
        return this.rozpoczecie;
    }
    
    public void setRozpoczecie(Date rozpoczecie) {
        this.rozpoczecie = rozpoczecie;
    }
    public Date getZakonczenie() {
        return this.zakonczenie;
    }
    
    public void setZakonczenie(Date zakonczenie) {
        this.zakonczenie = zakonczenie;
    }
    public Set getPracownicies() {
        return this.pracownicies;
    }
    
    public void setPracownicies(Set pracownicies) {
        this.pracownicies = pracownicies;
    }




}


